### ISSUE TITLE
build inconsistenly fails

### ISSUE THREAD

**Issue by kumavis** [caridy/secure-javascript-environment#40]
```
secure-javascript-environment on  master [?] is 📦 v0.1.0 via ⬢ v10.16.0 
⇡0% ➜ yarn build
yarn run v1.19.1
$ ttsc & rollup -c

examples/web-components/platform.js → examples/web-components/bundle.js...
[!] Error: Could not resolve '../../lib/browser-realm.js' from examples/web-components/platform.js
Error: Could not resolve '../../lib/browser-realm.js' from examples/web-components/platform.js
    at error (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:5362:30)
    at ModuleLoader.handleMissingImports (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:12200:17)
    at ModuleLoader.<anonymous> (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:12091:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:41:28)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

secure-javascript-environment on  master [?] is 📦 v0.1.0 via ⬢ v10.16.0 
⇡0% ➜ yarn build
yarn run v1.19.1
$ ttsc & rollup -c

examples/web-components/platform.js → examples/web-components/bundle.js...
[!] Error: Could not resolve '../../lib/browser-realm.js' from examples/web-components/platform.js
Error: Could not resolve '../../lib/browser-realm.js' from examples/web-components/platform.js
    at error (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:5362:30)
    at ModuleLoader.handleMissingImports (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:12200:17)
    at ModuleLoader.<anonymous> (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:12091:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xyz/Development/secure-javascript-environment/node_modules/rollup/dist/rollup.js:41:28)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

secure-javascript-environment on  master [?] is 📦 v0.1.0 via ⬢ v10.16.0 
⇡0% ➜ yarn build
yarn run v1.19.1
$ ttsc & rollup -c

examples/web-components/platform.js → examples/web-components/bundle.js...
created examples/web-components/bundle.js in 136ms
Done in 0.41s.

secure-javascript-environment on  master [?] is 📦 v0.1.0 via ⬢ v10.16.0 
⇡0% ➜ yarn build
yarn run v1.19.1
$ ttsc & rollup -c

examples/web-components/platform.js → examples/web-components/bundle.js...
created examples/web-components/bundle.js in 101ms
Done in 0.32s.

```

**Comment by danfinlay** [comment]
It seems that `/lib/browser-realm.js` is absent, and running build for me produces this same error.

**Comment by danfinlay** [comment]
My build failed on node 12, but I was able to get it to succeed on node `v10.17.2`.
